Revert "Setup MySQL root password"
This is currently breaking my local devtest (and probably
CI once we try running with it).  MysqlRootPassword is
defined in the Heat template as a Resource, and passing it
in as a parameter causes the error:

ERROR: The Parameter (MysqlRootPassword) was not defined in
template.

Closes-Bug: 1358914

This reverts commit 8b049e4ed31c5c7797bf7b867a0d8c90cee40a79.

Change-Id: Ie17decadef997e3ee0b19f951347797c13e02c65